#!/bin/bash

HOSTNAME=$(hostname)
TIMEZONE_NAME=$(timedatectl show --property=Timezone --value)
TIMEZONE_OFFSET=$(date +"%-:z" | sed 's/:[0-9]*$//')
USER=$(whoami)
OS=$(lsb_release -d | cut -f2)
DATE=$(date +"%d %b %Y %T")
UPTIME=$(uptime -p)
UPTIME_SEC=$(awk '{print $1}' /proc/uptime)
IP=$(ip -4 route get 8.8.8.8 | awk '{print $7}')
MASK=$(ifconfig | grep -w 'inet' | awk '{print $4}' | head -n 1)
GATEWAY=$(ip -4 route show default | awk '{print $3}')
RAM_TOTAL=$(free -h --total | awk '/^Mem:/ {printf "%.3f GB\n", $2/1024}')
RAM_USED=$(free -h | awk '/^Mem:/ {printf "%.3f GB\n", $3/1024}')
RAM_FREE=$(free -h | awk '/^Mem:/ {printf "%.3f GB\n", $4/1024}')
SPACE_ROOT=$(df -h / | awk '/\// {printf "%.2f MB\n", $2*1024}')
SPACE_ROOT_USED=$(df -h / | awk '/\// {printf "%.2f MB\n", $3*1024}')
SPACE_ROOT_FREE=$(df -h / | awk '/\// {printf "%.2f MB\n", $4*1024}')